version: "3.4"

volumes:
  keys:

services:
  saml-idp:
    container_name: saml-idp
    image: saml-idp
    build: .
    volumes:
      - keys:/application/keys
    environment:
      - HOST=0.0.0.0
    ports:
      - 127.0.0.1:7000:7000
